/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fan.glb 
Author: deslancer (https://sketchfab.com/deslancer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-universe-abstract-animation-5fd04e3bcaa2403eb1a9e3936355535d
Title: Table Universe Abstract Animation
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/3d/fan.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
   if (!actions) return;

   const actionNames = Object.keys(actions);
   if (actionNames.length === 0) return;

   const idle = actions[actionNames[0]];
   idle?.reset().fadeIn(0.5).play();

   return () => idle?.fadeOut(0.5);
 }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b779f3d002164ee4b136c15c00da1622fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Circle_1">
                  <group name="Cylinder_9" rotation={[0, 0, Math.PI / 4]}>
                    <mesh name="Cylinder_9_Blue-Chrome_0" geometry={nodes['Cylinder_9_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Sphere_3" position={[0, 8.512, 0]}>
                    <mesh name="Sphere_3_Blue-Chrome_0" geometry={nodes['Sphere_3_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_6" position={[0.009, -8.853, 0.007]}>
                    <mesh name="Cylinder_6_Blue-Chrome_0" geometry={nodes['Cylinder_6_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_1_Blue-Chrome_0" geometry={nodes['Circle_1_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Circle_2" position={[0, -0.202, 0]}>
                  <group name="Sphere_6" position={[-5.489, -5.123, 0]}>
                    <mesh name="Sphere_6_Blue-Chrome_0" geometry={nodes['Sphere_6_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder" position={[0.27, 1, 0]}>
                    <mesh name="Cylinder_Blue-Chrome_0" geometry={nodes['Cylinder_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_1" position={[0.27, 1, 0]}>
                    <mesh name="Cylinder_1_Blue-Chrome_0" geometry={nodes['Cylinder_1_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_2_Blue-Chrome_0" geometry={nodes['Circle_2_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Circle_3" position={[0, -0.186, 0]}>
                  <group name="Cylinder_2" position={[1.436, 1.436, 0]} rotation={[0, 0, -Math.PI / 4]}>
                    <mesh name="Cylinder_2_Blue-Chrome_0" geometry={nodes['Cylinder_2_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_3" position={[1.436, 1.436, 0]} rotation={[0, 0, -Math.PI / 4]}>
                    <mesh name="Cylinder_3_Blue-Chrome_0" geometry={nodes['Cylinder_3_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Sphere_5" position={[6.488, 0, 0]}>
                    <mesh name="Sphere_5_Blue-Chrome_0" geometry={nodes['Sphere_5_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_3_Blue-Chrome_0" geometry={nodes['Circle_3_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Circle_4" position={[0, -0.159, 0]}>
                  <group name="Cylinder_4" position={[0.27, 2.997, 0]}>
                    <mesh name="Cylinder_4_Blue-Chrome_0" geometry={nodes['Cylinder_4_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_5" position={[0.27, 2.997, 0]}>
                    <mesh name="Cylinder_5_Blue-Chrome_0" geometry={nodes['Cylinder_5_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Sphere_4" position={[3.756, -3.992, 0]}>
                    <mesh name="Sphere_4_Blue-Chrome_0" geometry={nodes['Sphere_4_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_4_Blue-Chrome_0" geometry={nodes['Circle_4_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Circle_5" position={[0, -0.122, 0]}>
                  <group name="Cylinder_7" position={[-2.833, 2.833, 0]} rotation={[0, 0, Math.PI / 4]}>
                    <mesh name="Cylinder_7_Blue-Chrome_0" geometry={nodes['Cylinder_7_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_8" position={[-2.833, 2.833, 0]} rotation={[0, 0, Math.PI / 4]}>
                    <mesh name="Cylinder_8_Blue-Chrome_0" geometry={nodes['Cylinder_8_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Sphere_2" position={[-4.455, 0, 0]}>
                    <mesh name="Sphere_2_Blue-Chrome_0" geometry={nodes['Sphere_2_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_5_Blue-Chrome_0" geometry={nodes['Circle_5_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Circle_6" position={[0, -0.122, 0]}>
                  <group name="Sphere_1" position={[-2.675, -2.245, 0]}>
                    <mesh name="Sphere_1_Blue-Chrome_0" geometry={nodes['Sphere_1_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_10" position={[0.27, 4.975, 0]}>
                    <mesh name="Cylinder_10_Blue-Chrome_0" geometry={nodes['Cylinder_10_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_11" position={[0.27, 4.975, 0]}>
                    <mesh name="Cylinder_11_Blue-Chrome_0" geometry={nodes['Cylinder_11_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_6_Blue-Chrome_0" geometry={nodes['Circle_6_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Circle_7">
                  <group name="Cylinder_12" position={[1.245, -1.263, 0]} rotation={[0, 0, Math.PI / 4]}>
                    <mesh name="Cylinder_12_Blue-Chrome_0" geometry={nodes['Cylinder_12_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Cylinder_13" position={[-1.245, 1.228, 0]} rotation={[0, 0, Math.PI / 4]}>
                    <mesh name="Cylinder_13_Blue-Chrome_0" geometry={nodes['Cylinder_13_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <group name="Sphere" position={[-2.515, 0, 0]}>
                    <mesh name="Sphere_Blue-Chrome_0" geometry={nodes['Sphere_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                  </group>
                  <mesh name="Circle_7_Blue-Chrome_0" geometry={nodes['Circle_7_Blue-Chrome_0'].geometry} material={materials['Blue-Chrome']} />
                </group>
                <group name="Center" rotation={[-1.46, -0.041, -1.141]}>
                  <group name="Platonic" position={[0.017, 0.007, 0.027]} rotation={[-0.936, -0.907, 1.017]}>
                    <mesh name="Platonic_Core-Grid_0" geometry={nodes['Platonic_Core-Grid_0'].geometry} material={materials['Core-Grid']} />
                  </group>
                  <group name="Cylinder_14" position={[0.405, -0.466, 1.361]} rotation={[-0.858, -0.924, 0.46]}>
                    <mesh name="Cylinder_14_Core_0" geometry={nodes.Cylinder_14_Core_0.geometry} material={materials.Core} />
                  </group>
                  <group name="Cylinder_15" position={[-0.392, 0.481, -1.349]} rotation={[-0.858, -0.924, 0.46]}>
                    <mesh name="Cylinder_15_Core_0" geometry={nodes.Cylinder_15_Core_0.geometry} material={materials.Core} />
                  </group>
                  <mesh name="Center_Core_0" geometry={nodes.Center_Core_0.geometry} material={materials.Core} />
                </group>
                <group name="CINEMA_4D_Editor" position={[-2.305, 5.574, 35.009]} rotation={[0, 1.432, -0.361]}>
                  <group name="Object_5" />
                </group>
                <group name="Base_1" position={[0, -10.64, 0]}>
                  <group name="holder_1" position={[9.979, 10.328, 0.041]}>
                    <mesh name="holder_1_Gold_0" geometry={nodes.holder_1_Gold_0.geometry} material={materials.Gold} />
                  </group>
                  <group name="Handle" position={[0, 5.291, 0]}>
                    <mesh name="Handle_Gold_0" geometry={nodes.Handle_Gold_0.geometry} material={materials.Gold} />
                  </group>
                  <group name="Base" position={[0, -1.77, 0]}>
                    <mesh name="Base_Base_0" geometry={nodes.Base_Base_0.geometry} material={materials.Base} />
                  </group>
                  <group name="holder" position={[-9.89, 10.328, 0.041]} rotation={[Math.PI, 0, Math.PI]}>
                    <mesh name="holder_Gold_0" geometry={nodes.holder_Gold_0.geometry} material={materials.Gold} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/fan.glb')
