/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.glb --transform 
Files: robot.glb [25.47MB] > D:\Web Development CWH\Projects\portfolio\New folder\rishank-portfolio\public\3d\robot-transformed.glb [3.73MB] (85%)
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-ob-robot-unit-th-icc02-animated-6c0764c2bc4c4aaa8e03ba1653f455a6
Title: Sci-fi O.B. Robot Unit TH-ICC02 (animated)
*/
"use client"
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'

export function Model(props) {
  
  const group = React.useRef()
  const { scene, animations } = useGLTF('/3d/robot-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
   if (!actions) return;

   const actionNames = Object.keys(actions);
   if (actionNames.length === 0) return;

   const idle = actions[actionNames[0]];
   idle?.reset().fadeIn(0.5).play();

   return () => idle?.fadeOut(0.5);
 }, [actions]);
 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Body3} skeleton={nodes.Object_7.skeleton} morphTargetDictionary={nodes.Object_7.morphTargetDictionary} morphTargetInfluences={nodes.Object_7.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Body3} skeleton={nodes.Object_9.skeleton} morphTargetDictionary={nodes.Object_9.morphTargetDictionary} morphTargetInfluences={nodes.Object_9.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Body3} skeleton={nodes.Object_13.skeleton} morphTargetDictionary={nodes.Object_13.morphTargetDictionary} morphTargetInfluences={nodes.Object_13.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Body3} skeleton={nodes.Object_11.skeleton} morphTargetDictionary={nodes.Object_11.morphTargetDictionary} morphTargetInfluences={nodes.Object_11.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Body3} skeleton={nodes.Object_15.skeleton} morphTargetDictionary={nodes.Object_15.morphTargetDictionary} morphTargetInfluences={nodes.Object_15.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.01} />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material_0_Merged0_LOD0_Bake} skeleton={nodes.Object_17.skeleton} morphTargetDictionary={nodes.Object_17.morphTargetDictionary} morphTargetInfluences={nodes.Object_17.morphTargetInfluences} rotation={[-1.566, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/robot-transformed.glb')
